import "./globals.css";

import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import { ReactNode } from "react";

import Providers from "@/components/Providers";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";

const font = Plus_Jakarta_Sans();

export const metadata: Metadata = {
  title: "Mero",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>
        <Providers>
          <div className="h-screen flex overflow-hidden">
            <Navbar />

            <Sidebar />

            <div className="flex-1 min-h-screen overflow-y-scroll no-scrollbar">
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
